services:
  - type: web
    name: tau-events-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromConfigVar: MONGO_URI
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://tau-events.vercel.app
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
